#!/bin/bash

SCRIPTPATH=$(dirname "$0")

if [[ -z "$1" || -z "$2" ]]; then
    echo "Please provide input cpp file (\$1) and project name (\$2)"
    exit 1;
fi

"$SCRIPTPATH/ev3build" "$1" "./tmp" && "$SCRIPTPATH/ev3upload" "./tmp" "$2" && echo "** Cleaning up..." && rm "./tmp" && echo "** Complete." || exit 1;
